# Generated by Django 4.1.5 on 2023-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerifyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captcha", models.CharField(max_length=20, verbose_name="captcha")),
                ("email", models.EmailField(max_length=50, verbose_name="email")),
                (
                    "send_type",
                    models.CharField(
                        choices=[("register", "register"), ("forget", "forget")],
                        default="register",
                        max_length=10,
                    ),
                ),
                (
                    "send_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="time"),
                ),
            ],
            options={
                "verbose_name": "email captcha",
                "verbose_name_plural": "email captcha",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户数据", "verbose_name_plural": "用户数据"},
        ),
    ]
