# Generated by Django 4.1.5 on 2023-01-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_emailverifyrecord_alter_userprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="desc",
            field=models.TextField(
                blank=True, default="", max_length=200, verbose_name="decription"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="motto",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="motto"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(
                blank=True, default="", null=True, verbose_name="birth date"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女")],
                default="male",
                max_length=6,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nike_name",
            field=models.CharField(
                blank=True, default="", max_length=23, verbose_name="nickname"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
