# Generated by Django 4.1.5 on 2023-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_desc_userprofile_motto_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="desc",),
        migrations.AddField(
            model_name="userprofile",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=200, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(
                blank=True, default="", null=True, verbose_name="birthday"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nike_name",
            field=models.CharField(
                blank=True, default="", max_length=23, verbose_name="nick_name"
            ),
        ),
    ]
