# Generated by Django 4.1.5 on 2023-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userprofile_desc_userprofile_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "user data", "verbose_name_plural": "user data"},
        ),
        migrations.RenameField(
            model_name="userprofile", old_name="nike_name", new_name="nick_name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=6,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/%Y/%m",
                verbose_name="User Image",
            ),
        ),
    ]
