# Generated by Django 4.1.5 on 2023-01-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户数据", "verbose_name_plural": "用户数据"},
        ),
    ]
