# Generated by Django 4.1.5 on 2023-01-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="category name")),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="category desc",
                    ),
                ),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="add date"),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now=True, verbose_name="modify date"),
                ),
            ],
            options={
                "verbose_name": "blog category",
                "verbose_name_plural": "blog category",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="文章标签")),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("pub_date", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
            ],
            options={"verbose_name": "文章标签", "verbose_name_plural": "文章标签",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=61, verbose_name="article title"),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="article description",
                    ),
                ),
                ("content", models.TextField(verbose_name="article content")),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                ("pv", models.IntegerField(default=0, verbose_name="浏览量")),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("pub_date", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.tag",
                        verbose_name="文章标签",
                    ),
                ),
            ],
            options={"verbose_name": "文章", "verbose_name_plural": "文章",},
        ),
    ]
