# Generated by Django 4.1.5 on 2023-01-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sidebar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="模块名称")),
                (
                    "display_type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "搜索"),
                            (2, "最新文章"),
                            (3, "最热文章"),
                            (4, "最近评论"),
                            (5, "文章归档"),
                            (6, "HTML"),
                        ],
                        default=1,
                        verbose_name="展示类型",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如果设置的不是HTML类型，可为空",
                        max_length=500,
                        verbose_name="内容",
                    ),
                ),
                (
                    "sort",
                    models.PositiveIntegerField(
                        default=1, help_text="序号越大越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "隐藏"), (2, "展示")], default=2, verbose_name="状态"
                    ),
                ),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "侧边栏",
                "verbose_name_plural": "侧边栏",
                "ordering": ["-sort"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Category",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Articles", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Article Tags",
                "verbose_name_plural": "Article Tags",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Add Date"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Article Content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc",
            field=models.TextField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Article Description",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_hot",
            field=models.BooleanField(default=False, verbose_name="Whether hot?"),
        ),
        migrations.AlterField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modify Date"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pv",
            field=models.IntegerField(default=0, verbose_name="Page View"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.tag",
                verbose_name="Article Tags",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=61, verbose_name="Article Title"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Add Date"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10, verbose_name="Article Tags"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modify Date"),
        ),
    ]
